service: missions-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage}
  region: ${env:AWS_LAMBDA_REGION, 'us-east-1'}

functions:
  app:
    handler: build/server.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"
    environment:
      VERIDA_NETWORK: ${env:VERIDA_NETWORK, 'devnet'}
      NOTION_API_KEY: ${env:NOTION_API_KEY}
      AIRDROP_1_NOTION_DB_ID: ${env:AIRDROP_1_NOTION_DB_ID}
      AIRDROP_2_NOTION_DB_ID: ${env:AIRDROP_2_NOTION_DB_ID}
      AIRDROPS_SENDER_ACCOUNT_PRIVATE_KEY: ${env:AIRDROPS_SENDER_ACCOUNT_PRIVATE_KEY}
      BLOCKCHAIN_VDA_CONTRACT_ADDRESS: ${env:BLOCKCHAIN_VDA_CONTRACT_ADDRESS}
      BLOCKCHAIN_RPC_URL: ${env:BLOCKCHAIN_RPC_URL}
      BLOCKCHAIN_TRANSACTION_EXPLORER_URL: ${env:BLOCKCHAIN_TRANSACTION_EXPLORER_URL}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

custom:
  serverless-offline:
    httpPort: ${env:PORT, '5022'}
    noPrependStageInUrl: true
    useChildProcesses: true
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - npm_config_platform=linux npm_config_arch=x64 yarn add leveldown ## TODO: Check if still necessary

package:
  patterns:
    - "!node_modules/**"
