export const POLYGON_MAINNET_CHAIN_ID = "eip155:137";
export const POLYGON_AMOY_CHAIN_ID = "eip155:80002";

export const SUPPORTED_BLOCKCHAINS = [
  POLYGON_MAINNET_CHAIN_ID,
  POLYGON_AMOY_CHAIN_ID,
];
