name: CI

on:
  workflow_dispatch:
  push:

# Avoid having two runs of the same workflow for the same reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Define node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check linting and formatting
        run: yarn run check

      - name: Check build
        run: yarn run build

      # TODO: Fix unit tests first
      # - name: Unit tests
      #   run: yarn run test
